apiVersion: v1
kind: Service
metadata:
  name: my-calculator-app-service
  namespace: calculator-stg
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: my-calculator-app